### ISSUE TITLE
路过图床不能登录  

### ISSUE THREAD

**Issue by xsunnydong** [thep0y/up2b#10]
路过图床不能登录  
使用的版本：[0.7.1-alpha.10](https://github.com/thep0y/up2b/releases/tag/v0.7.1-alpha.10)
使用的命令： up2b login 用户名 密码
提示：up2b.up2b_lib.errors.MissingAuth: auth token or cookie is None

**Comment by thep0y** [comment]
路过可能改了一些逻辑，加入一些验证过程，有时间我会适配一下。

**Comment by thep0y** [comment]
试一下这个版本  https://www.123pan.com/s/Q61bVv-hzAvd.html

**Comment by thep0y** [comment]
已上传 up2b-rs 代码，配置文件与此项目不同，可完全代替使用。

https://github.com/thep0y/up2b-rs
