### ISSUE TITLE
大佬这个做的真是NB，就是上传后能不能返回下直链呢？

### ISSUE THREAD

**Issue by longhuishen** [thep0y/up2b#5]
我放vps上运行 就想上传个图片到路过后返回直链
#!/bin/bash
up2b -c 1
sleep 2
up2b -l  admin password
sleep 2
up2b -p '1.jpg'
echo '完成'

**Comment by thep0y** [comment]
up2b -ps 会输出图片链接，-p不会。发自我的 iPhone在 2023年2月4日，21:18，longhuishen ***@***.***> 写道：﻿
我放vps上运行 就想上传个图片后返回链
#!/bin/bash up2b -c 1 sleep 2 up2b -l  admin password sleep 2 up2b -p '1.jpg' echo '完成'

**Comment by longhuishen** [comment]
> up2b -ps 会输出图片链接，-p不会。发自我的 iPhone在 2023年2月4日，21:18，longhuishen ***@***.***> 写道：﻿
> 我放vps上运行 就想上传个图片后返回链
> #!/bin/bash up2b -c 1 sleep 2 up2b -l  admin password sleep 2 up2b -p '1.jpg' echo '完成'
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

感谢，大佬，返回了。

大佬，如果我想直接在Python里直接import  up2b后使用，  上传图片到路过同时得到直链并传给一个变量，怎么搞呢，大佬可以给个例子吗，非常感谢。

**Comment by thep0y** [comment]
```python
from up2b.up2b_lib.utils import logger
from up2b.up2b_lib.up2b_api.imgtu import Imgtu


def upload():
    im = Imgtu()

    print("正在上传图片...")
    res = im.upload_image("/path/image.png")
    if isinstance(res, str):
        print("图片已上传：", res)
    else:
        logger.fatal("上传出错：%s", res)


if __name__ == "__main__":
    with logger:
        upload()

```

**Comment by longhuishen** [comment]
> ```python
> from up2b.up2b_lib.utils import logger
> from up2b.up2b_lib.up2b_api.imgtu import Imgtu
> 
> 
> def upload():
>     im = Imgtu()
> 
>     print("正在上传图片...")
>     res = im.upload_image("/path/image.png")
>     if isinstance(res, str):
>         print("图片已上传：", res)
>     else:
>         logger.fatal("上传出错：%s", res)
> 
> 
> if __name__ == "__main__":
>     with logger:
>         upload()
> ```

感谢大佬指导，我试了下，提示要登录，我看了下应该要调用login()，但加了个Im.login()调用了login又提示超时。
发生异常: SSLError
HTTPSConnectionPool(host='imgse.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

> ```python
> from up2b.up2b_lib.utils import logger
> from up2b.up2b_lib.up2b_api.imgtu import Imgtu
> 
> 
> def upload():
>     im = Imgtu()
>     im.login("2233@qq.com","Z00022020")
>     print("正在上传图片...")
>     res = im.upload_image("/path/image.png")
>     if isinstance(res, str):
>         print("图片已上传：", res)
>     else:
>         logger.fatal("上传出错：%s", res)
> 
> 
> if __name__ == "__main__":
>     with logger:
>         upload()
> ```

**Comment by thep0y** [comment]
> 感谢大佬指导，我试了下，提示要登录，我看了下应该要调用login()，但加了个Im.login()调用了login又提示超时。 发生异常: SSLError HTTPSConnectionPool(host='imgse.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))) ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

登录信息保存在本地配置文件中，登录一次以后上传图片时会自动登录，除非你上传完就删除了配置文件。

超时很正常，多试几次。
如果一直超时，上传完整错误日志。

**Comment by longhuishen** [comment]
> > 感谢大佬指导，我试了下，提示要登录，我看了下应该要调用login()，但加了个Im.login()调用了login又提示超时。 发生异常: SSLError HTTPSConnectionPool(host='imgse.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))) ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
> 
> 登录信息保存在本地配置文件中，登录一次以后上传图片时会自动登录，除非你上传完就删除了配置文件。
> 
> 超时很正常，多试几次。 如果一直超时，上传完整错误日志。
感谢  放VPS试了下  成功上传 返回链接  非常完美   帮我解决了大问题 
还有 upload_image() 是不是只能上传本地图片  如果直接上传链接好像会报错，比如https://uploads2.xiegw.cn/yc/20211222/d0620f8efd28c9c3d52eba5a8fa9af49.jpg

**Comment by thep0y** [comment]
> > >
> 
> 感谢大佬指导，我试了下，提示要登录，我看了下应该要调用login()，但加了个Im.login()调用了login又提示超时。 发生异常: SSLError HTTPSConnectionPool(host='imgse.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))) ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
> 
> > 登录信息保存在本地配置文件中，登录一次以后上传图片时会自动登录，除非你上传完就删除了配置文件。
> > 超时很正常，多试几次。 如果一直超时，上传完整错误日志。
> 
> 感谢 放VPS试了下 成功上传 返回链接 非常完美 帮我解决了大问题 还有 upload_image() 是不是只能上传本地图片 如果直接上传链接好像会报错，比如https://uploads2.xiegw.cn/yc/20211222/d0620f8efd28c9c3d52eba5a8fa9af49.jpg

现在不支持上传在线图片，以后应该会添加此功能。

**Comment by longhuishen** [comment]
> > > >
> > 
> > 感谢大佬指导，我试了下，提示要登录，我看了下应该要调用login()，但加了个Im.login()调用了login又提示超时。 发生异常: SSLError HTTPSConnectionPool(host='imgse.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))) ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
> > 
> > > 登录信息保存在本地配置文件中，登录一次以后上传图片时会自动登录，除非你上传完就删除了配置文件。
> > > 超时很正常，多试几次。 如果一直超时，上传完整错误日志。
> > 
> > 感谢 放VPS试了下 成功上传 返回链接 非常完美 帮我解决了大问题 还有 upload_image() 是不是只能上传本地图片 如果直接上传链接好像会报错，比如https://uploads2.xiegw.cn/yc/20211222/d0620f8efd28c9c3d52eba5a8fa9af49.jpg
> 
> 现在不支持上传在线图片，以后应该会添加此功能。

好的

**Comment by thep0y** [comment]
@longhuishen 没有别的问题的话就关了 issue 吧
