### ISSUE TITLE
大佬 路过图床是不是报错了

### ISSUE THREAD

**Issue by longhuishen** [thep0y/up2b#7]
正在上传图片...
[90m09:30:04.527[0m [37m[[0m[31mFAT[0m[37m][0m [36mup2b [0m[96m-[0m 上传出错：UploadErrorResponse(status_code=400, error='Envoi dupliqué', image_path='1.jpg')

**Comment by thep0y** [comment]
@longhuishen 这个问题看起来像是路过开启了防止图片二次上传的功能，而且返回的错误中还不包含之前上传过的图片的链接。之前也开启过，我也问过站长，给的回复是，懒得改了，自己去找一下重复图片吧。

**Comment by longhuishen** [comment]
应该是没有重复图片的，因为每天都是从央广网当天更新的图片下载的

**Comment by longhuishen** [comment]
3月20日不行的，刚我在浏览器中手动登录了下路过图床  又行了

**Comment by thep0y** [comment]
@thep0y 我只能保证程序运行是正常的，路过出现什么问题我不能预知，也不知道怎么解决，所以我不用路过

**Comment by longhuishen** [comment]
好的 感谢大佬
